const CartActionType={
    TOFFLE_CART_HIDDEN:'TOFFLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    REMOVE_ITEM:'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART:'CLEAR_ITEM_FROM_CART:',
    CLEAR_CART:'CLEAR_CART'
};

export default CartActionType;